environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      APPVEYOR_JOB_NAME: "linux-x64"

    - PYTHON: "Python310"
      BUILD_ARCH: "x86"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python311"
      BUILD_ARCH: "x86"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python312"
      BUILD_ARCH: "x86"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python313"
      BUILD_ARCH: "x86"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

    - PYTHON: "Python310-x64"
      BUILD_ARCH: "x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python311-x64"
      BUILD_ARCH: "x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python312-x64"
      BUILD_ARCH: "x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python313-x64"
      BUILD_ARCH: "x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

stack: python 3.12

install:
  - sh: python -m pip install --upgrade pip
  - sh: python -m pip install cibuildwheel==2.21.3

build_script:
#  - '.\venv\Scripts\python setup.py build_ext --inplace'
#  - '.\venv\Scripts\python setup.py bdist_wheel'
  - cmd: 'move omniORBpy omniORB\src\lib'

  - cmd: 'cd omniORB'
  - cmd: 'set PATH=%PATH%;%CD%\bin\x86_win32'

  # doesn't work: - 'echo platform = x86_win32_vs_14>>config\config.mk'
  - cmd: 'sed -i "s/.*Uncomment one of the following platform lines.*/platform = x86_win32_vs_14/" config/config.mk'
  - cmd: 'echo PYTHON = /cygdrive/c/%PYTHON%/python>>mk\platforms\x86_win32_vs_14.mk'

# install cygwin make
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %BUILD_ARCH%'
  - cmd: 'set path=%path%;c:\cygwin\bin;c:\%PYTHON%'
  - cmd: 'set path=c:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86;c:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x86\;%PATH%'
  - cmd: 'cd src'
  - cmd: 'make export'
  - cmd: 'cd lib\omniORBpy'
  - cmd: 'make export'
  - cmd: 'cd ..\..\..\..'
  - cmd: 'c:\%PYTHON%\python.exe -m pip install wheel setuptools'
  - cmd: 'c:\%PYTHON%\python.exe setup.py bdist_wheel'

# Generate wheels for Linux CPython x86_64 3.10+
  - sh: python -m cibuildwheel --output-dir dist

artifacts:
  - path: 'dist/*whl'
    name: Wheels

test: false
